package net.arcanamod.worldgen;

import net.minecraft.util.ResourceLocation;
import net.minecraft.world.storage.loot.LootTable;
import net.minecraft.world.storage.loot.LootTables;

public enum LootTableGroups {
	EVERYWHERE,
	ORE,
	VILLAGES(LootTables.CHESTS_VILLAGE_VILLAGE_ARMORER,LootTables.CHESTS_VILLAGE_VILLAGE_BUTCHER,LootTables.CHESTS_VILLAGE_VILLAGE_CARTOGRAPHER,LootTables.CHESTS_VILLAGE_VILLAGE_DESERT_HOUSE,
			 LootTables.CHESTS_VILLAGE_VILLAGE_FISHER,LootTables.CHESTS_VILLAGE_VILLAGE_FLETCHER,LootTables.CHESTS_VILLAGE_VILLAGE_MASON,LootTables.CHESTS_VILLAGE_VILLAGE_PLAINS_HOUSE,
			 LootTables.CHESTS_VILLAGE_VILLAGE_SAVANNA_HOUSE,LootTables.CHESTS_VILLAGE_VILLAGE_SHEPHERD,LootTables.CHESTS_VILLAGE_VILLAGE_SNOWY_HOUSE,LootTables.CHESTS_VILLAGE_VILLAGE_TAIGA_HOUSE,
			 LootTables.CHESTS_VILLAGE_VILLAGE_TANNERY,LootTables.CHESTS_VILLAGE_VILLAGE_TEMPLE,LootTables.CHESTS_VILLAGE_VILLAGE_TOOLSMITH,LootTables.CHESTS_VILLAGE_VILLAGE_WEAPONSMITH),

	MINES(LootTables.CHESTS_ABANDONED_MINESHAFT),

	BONUS_CHEST(LootTables.CHESTS_SPAWN_BONUS_CHEST),

	RUINS(LootTables.CHESTS_UNDERWATER_RUIN_BIG,LootTables.CHESTS_UNDERWATER_RUIN_SMALL,
		  LootTables.CHESTS_SHIPWRECK_TREASURE,LootTables.CHESTS_SHIPWRECK_TREASURE,LootTables.CHESTS_SHIPWRECK_MAP),

	STRUCTURES(LootTables.CHESTS_IGLOO_CHEST,LootTables.CHESTS_JUNGLE_TEMPLE,
			   LootTables.CHESTS_PILLAGER_OUTPOST,LootTables.CHESTS_DESERT_PYRAMID),

	BASTIONS(LootTables.CHESTS_NETHER_BRIDGE),

	END_CITY(LootTables.CHESTS_END_CITY_TREASURE),

	MANSION(LootTables.CHESTS_WOODLAND_MANSION),

	DUNGEON(LootTables.CHESTS_SIMPLE_DUNGEON,LootTables.CHESTS_STRONGHOLD_CORRIDOR,
			LootTables.CHESTS_STRONGHOLD_CROSSING,LootTables.CHESTS_STRONGHOLD_LIBRARY),

	BURIED_CHEST(LootTables.CHESTS_BURIED_TREASURE);

	public ResourceLocation[] lootTables;

	LootTableGroups(ResourceLocation... lootTables){
		this.lootTables = lootTables;
	}

	LootTableGroups(){
		this.lootTables = null;
	}
}
